INSERT INTO category (description, color) VALUES ('Food & Restaurants', '#ff6347');
INSERT INTO category (description, color) VALUES ('Car', '#1e90ff');
INSERT INTO category (description, color) VALUES ('Subscriptions', '#8a2be2');
INSERT INTO category (description, color) VALUES ('Entertainment', '#ff4500');
INSERT INTO category (description, color) VALUES ('Education', '#3cb371');
INSERT INTO category (description, color) VALUES ('Saving', '#ffd700');
INSERT INTO category (description, color) VALUES ('Clothing', '#ff69b4');
INSERT INTO category (description, color) VALUES ('Housing', '#20b2aa');
INSERT INTO category (description, color) VALUES ('Health', '#db7093');

INSERT INTO currency (code) VALUES ('RON');
INSERT INTO currency (code) VALUES ('MDL');
INSERT INTO currency (code) VALUES ('EUR');
INSERT INTO currency (code) VALUES ('USD');
INSERT INTO currency (code) VALUES ('GBP');
INSERT INTO currency (code) VALUES ('CAD');
INSERT INTO currency (code) VALUES ('CHF');
INSERT INTO currency (code) VALUES ('HUF');
INSERT INTO currency (code) VALUES ('CZK');
INSERT INTO currency (code) VALUES ('PLN');