INSERT INTO category (description, color) VALUES ('Food & Restaurants', '#4F46E5');
INSERT INTO category (description, color) VALUES ('Car', '#1EB3DB');
INSERT INTO category (description, color) VALUES ('Subscriptions', '#E83FAB');
INSERT INTO category (description, color) VALUES ('Entertainment', '#FF8084');
INSERT INTO category (description, color) VALUES ('Coffee', '#9FD11F');
INSERT INTO category (description, color) VALUES ('Education', '#FFD700');
INSERT INTO category (description, color) VALUES ('Saving', '#FFA500');
INSERT INTO category (description, color) VALUES ('Clothing', '#FF69B4');
INSERT INTO category (description, color) VALUES ('Housing', '#8B4513');
INSERT INTO category (description, color) VALUES ('Health', '#FF6347');

INSERT INTO currency (code) VALUES ('RON');
INSERT INTO currency (code) VALUES ('MDL');
INSERT INTO currency (code) VALUES ('EUR');
INSERT INTO currency (code) VALUES ('USD');
INSERT INTO currency (code) VALUES ('GBP');
INSERT INTO currency (code) VALUES ('CAD');
INSERT INTO currency (code) VALUES ('CHF');
INSERT INTO currency (code) VALUES ('HUF');
INSERT INTO currency (code) VALUES ('CZK');
INSERT INTO currency (code) VALUES ('PLN');